version: '3'

services:
  db:
    image: mongo
    container_name: nestDB
    environment:
      MONGO_INITDB_DATABASE: nestDB
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./docker-data/mongodb:/data

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:password@db:27017/
      ME_CONFIG_BASICAUTH: true

    volumes:
      - ./docker-data/mongodb-express:/data
